format = """
$username\
@\
$hostname\
:\
$directory\
$git_branch\
$git_state\
$git_status\
$line_break\
$character"""

[username]
show_always = true
format = '[$user]($style)'

[hostname]
ssh_only = false
format = '[$hostname]($style)'

[directory]
style = "blue"
truncate_to_repo = false
truncation_length = 3
truncation_symbol = "[..]/"

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](blue)"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"
